### ISSUE TITLE
ccl-bin chokes on :HOME

### ISSUE THREAD

**Issue by ak-coram** [40ants/setup-lisp#26]
This already happens during the setup, I had to remove `~/.roswell/init.lisp` to use Roswell after this step:

```
Checking if we installed correct Lisp implementation
  > Error: Invalid pathname component :HOME
  > While executing: CCL::%PATH-STD-QUOTES, in process listener(1).
  > Type :GO to continue, :POP to abort, :R for a list of available restarts.
  > If continued: Skip evaluation of (ros:run '((:eval"(ros:asdf)")(:eval"(ros:quicklisp)")(:load"/home/runner/.roswell/init.lisp")(:script "/home/runner/work/_actions/40ants/setup-lisp/v4/test.ros")(:quit ())))
  > Type :? for other options.
  1 > ::endgroup::
```

**Comment by svetlyak40wt** [comment]
I believe I've already fixed this bug in the new version of setup-lisp.

Please, try version `v4`.

**Comment by ak-coram** [comment]
I've seen it in the changelog for v3, but I'm already using v4

**Comment by ak-coram** [comment]
I've actually encountered this while trying to upgrade to v4 from v2: https://github.com/ak-coram/cl-duckdb/pull/61

**Comment by svetlyak40wt** [comment]
Could you please give a link to a CI build with the fail?

**Comment by ak-coram** [comment]
I've made you a contributor so you should be able to view this for example:
https://github.com/ak-coram/cl-duckdb/actions/runs/8657543117/job/23739842923

**Comment by svetlyak40wt** [comment]
This is interesting, the CCL-BIN build was market as "success", but failed to check if proper CCL was installed. Actually, I've put huge amount of time making such situation impossible – job should fail in this case :(

**Comment by svetlyak40wt** [comment]
I recall, the job was done there and everything I need is to update a table of supported implementations. Could you please check your workflow using `setup-lisp@fix-ql-fix-loading` branch?

**Comment by ak-coram** [comment]
Thanks, that branch seems to solve the issue:

https://github.com/ak-coram/cl-duckdb/actions/runs/8668217812/job/23772835357

**Comment by svetlyak40wt** [comment]
Ok, I'm working on the merge.

**Comment by ak-coram** [comment]
> This is interesting, the CCL-BIN build was market as "success", but failed to check if proper CCL was installed. Actually, I've put huge amount of time making such situation impossible – job should fail in this case :(

It's only marked as a success because I have set `continue-on-error: true` for this step. The reason I have this enabled is because sometimes the setup "fails", but the implementation is still usable (I remember such cases on Windows)

**Comment by svetlyak40wt** [comment]
@ak-coram I've merged the fix into the master branch and moved `v4` tag to this new version.
