### ISSUE TITLE
Cache key should probably include the OS version (e.g. macos-13 vs. macos-14)

### ISSUE THREAD

**Issue by ak-coram** [40ants/setup-lisp#32]
For macos-14 even the CPU architecture is different, so restoring the cache from macos-13 fails:

https://github.com/ak-coram/cl-duckdb/actions/runs/8699199541/job/23857402339

Right now the key looks like `roswell-v23.10.14.114-2024-04--macOS-sbcl-bin-v9`

**Comment by ak-coram** [comment]
Perhaps adding `$ImageVersion` to it would be sufficient? I think the cache might otherwise break under different circumstances (such as `ubuntu-latest` getting updated, etc.)

**Comment by svetlyak40wt** [comment]
Could you please make a pull-request?
