### ISSUE TITLE
SBCL is always used

### ISSUE THREAD

**Issue by neil-lindquist** [40ants/setup-lisp#5]
The current script always uses SBCL, regardless of `matrix.lisp`.  This can be fixed by setting `echo "LISP=${{ matrix.lisp }}" >> $GITHUB_ENV` in a previous step.

Searching for `ros use` in the following logs demonstrates the issue.  The only difference in the configurations is the addition of a step to add LISP to GITHUB_ENV.

Log without explicitly setting the env var:  https://pipelines.actions.githubusercontent.com/serviceHosts/4ff052d4-f731-4f0f-ba79-e8387896f7a4/_apis/pipelines/1/runs/6/signedlogcontent/3?urlExpires=2022-07-12T23%3A51%3A59.5506368Z&urlSigningMethod=HMACV1&urlSignature=2NJ0j0klobQrZ9KrUiHhslHxBcrKnUVoQgrW%2F6R9tlo%3D

Log with explicitly setting the env var:  https://pipelines.actions.githubusercontent.com/serviceHosts/4ff052d4-f731-4f0f-ba79-e8387896f7a4/_apis/pipelines/1/runs/8/signedlogcontent/3?urlExpires=2022-07-12T23%3A52%3A22.1776391Z&urlSigningMethod=HMACV1&urlSignature=YGN3lqKsZn6lSv0mg9A2oGr4gZsiIwXxsTHEKgOUW14%3D

Corresponding rich text logs:
https://github.com/neil-lindquist/linear-programming/runs/7311800636?check_suite_focus=true
https://github.com/neil-lindquist/linear-programming/runs/7311972487?check_suite_focus=true

**Comment by svetlyak40wt** [comment]
Your [ci.yaml](https://github.com/neil-lindquist/linear-programming/blob/master/.github/workflows/ci.yml) is incomplete.

This piece of config:

```
strategy:
      # Each combination of lisp and os are tested
      matrix:
        lisp: [sbcl-bin, ccl-bin]
        os: [windows-latest, ubuntu-latest, macOS-latest]
```

does not set environment variable itself. You need to add `env` section, as shown in the [documentation](https://40ants.com/setup-lisp/#x-28PROJECT-DOCS-3A-3A-40TYPICAL-USAGE-2040ANTS-DOC-2FLOCATIVES-3ASECTION-29):

<img width="615" alt="image" src="https://user-images.githubusercontent.com/24827/178842737-6f7bfc9f-929f-488a-9f87-0f6a80fadc02.png">

By the way, [here is how this looks like](https://github.com/40ants/reblocks/blob/master/.github/workflows/ci.yml#L22) in my workflow, autogenerated by [40ants-ci](https://40ants.com/ci/).

I think the documentation should be changed to make an explicit note about necessarity of the `LISP` environment variable in case if you want something other than default `sbcl-bin`.

**Comment by neil-lindquist** [comment]
I really don't know how I over looked that.  Thanks.
