### ISSUE TITLE
Setting up the Qlot Environment doesn't work on Windows

### ISSUE THREAD

**Issue by ak-coram** [40ants/setup-lisp#7]
This is the error from the logs:

```
Create Qlot Environment
  D:\a\_temp\56c48731-7e2a-4f7e-9c8a-e93589ec00df: line 4: D:a_actions40antssetup-lispv2/templater.ros: No such file or directory
  Error: Process completed with exit code 127.
```

Please let me know if you need further details.

**Comment by svetlyak40wt** [comment]
It would be cool to fix this issue, but Windows support was contributed by @iamFIREcracker. Probably he knows how to fix this.

Anyway, if you'll be able to figure out how to fix it, I'll be happy to review a pull-request!

**Comment by svetlyak40wt** [comment]
I've made this empty PR just to check if our tests will pass on Windows: https://github.com/40ants/setup-lisp/pull/8

**Comment by svetlyak40wt** [comment]
It is interesting, but setup-lisp's test was run successfully: https://github.com/40ants/setup-lisp/actions/runs/5143570413/jobs/9258750343

Probably this is something in your environment that makes action fail. Full log of the action run and code of the workflow would help to investigate this issue.

**Comment by ak-coram** [comment]
Thanks for helping with this! I'm not very familiar with Windows either, but would still be nice to have it working. 

Here's the full workflow (I've removed Windows from the matrix for now because of this issue):
https://github.com/ak-coram/cl-duckdb/blob/main/.github/workflows/CI.yml

I don't think I'm doing anything special here and I've taken the section for `qlfile-template` directly from the documentation.

The full log:
[CI.log](https://github.com/40ants/setup-lisp/files/11627323/CI.log)
